export { ReactComponent as FolderOpenFill } from './folder-open-fill.svg';
export { ReactComponent as Add } from './add-24.svg';
export { ReactComponent as ChevronDown } from './chevron-down.svg';
export { ReactComponent as ChevronUp } from './chevron-up.svg';
export { ReactComponent as Documents } from './documents.svg';
export { ReactComponent as DocumentsBlue } from './documents-blue.svg';
export { ReactComponent as Download } from './download.svg';
export { ReactComponent as Truck } from './truck.svg';
export { ReactComponent as Employee } from './employee.svg';
export { ReactComponent as Ticket } from './ticket.svg';
export { ReactComponent as Checkmark } from './check.svg';
export { ReactComponent as Pill } from './pill.svg';
export { ReactComponent as Back } from './back.svg';
export { ReactComponent as User } from './user.svg';
export { ReactComponent as Cancel } from './cancel.svg';
export { ReactComponent as Delete } from './delete.svg';
export { ReactComponent as Pen } from './pen.svg';
export { ReactComponent as Burger } from './burger.svg';
export { ReactComponent as Replay } from './replay.svg';
export { AllCategories } from './AllCategories';
export { SidebarTruck } from './SidebarTruck';

export { IconWithBackground } from './IconWithBackground';
